### ISSUE TITLE
changelog / release notes

### ISSUE THREAD

**Issue by robjtede** [akubera/bigdecimal-rs#104]
Please consider keeping a changelog in-tree or creating GitHub releases associated with version tags.

Came here today to find out what changed from 0.3.x -> 0.4.0 but can't find any details. Squinting at the commit log is not the most friendly way of figuring it out.

Thanks for your consideration.

**Comment by akubera** [comment]
Yeah, that's always something I mean to do and never get around to doing. I apparently never even created a "Release" on here github for 0.3.1.

**Comment by akubera** [comment]
Changelog written: 

https://github.com/akubera/bigdecimal-rs/releases/tag/v0.4.0

Thanks for the push to do that.
