### ISSUE TITLE
release the build.rs fix

### ISSUE THREAD

**Issue by rukai** [akubera/bigdecimal-rs#107]
bigdecimal is being rebuilt in my project constantly.
A 0.4.1 release to address this would be much appreciated, thanks.

Edit: oh, maybe I should have just left a comment here https://github.com/akubera/bigdecimal-rs/issues/105 sorry for the noise

**Comment by akubera** [comment]
v0.4.1 has been pushed!

I had a couple more things I thought I could implement more quickly than I did.

The rebuilds should stop now: let me know if they don't and we'll push a fix for it (and _only_ for it).

I'll leave this open until you confirm it works.

**Comment by rukai** [comment]
I won't have access to a computer till Monday (on holidays)
Will test and get back to you on monday

**Comment by rukai** [comment]
I can confirm the fix works, thanks for the quick turnaround!
