### ISSUE TITLE
Release 0.4.4 needs to be yanked.

### ISSUE THREAD

**Issue by rukai** [akubera/bigdecimal-rs#130]
https://github.com/akubera/bigdecimal-rs/issues/128#issuecomment-2171789517 explained the issue well, but I'm raising another issue to make it clear that 0.4.4 should be yanked while you figure out a full fix.
I've seen this cause `cargo update` to result in an unbuildable project and I'm sure it will cause issues across the ecosystem.

![image](https://github.com/akubera/bigdecimal-rs/assets/5120858/b2d3b565-260b-4f33-89ec-9dfe576f90d8)

**Comment by akubera** [comment]
v0.4.5 is out now. Let me know if that fixes it.

**Comment by rukai** [comment]
Thankyou, 0.4.5 solves the issue, the swift response is much appreciated.
