### ISSUE TITLE
impl rounding methods

### ISSUE THREAD

**Issue by rubdos** [akubera/bigdecimal-rs#14]
Especially needed/useful for calculating things like VAT, but I can imagine other people needing rounding methods.

**Comment by ArtemGr** [comment]
FYI, I've implemented a rounding specific to our use case (falling back to i64 to propagate the rounding to the integer part): https://github.com/KomodoPlatform/atomicDEX-API/commit/36d5bd9763584789deaa43bea82a59094c474a78. Maybe it will be useful as a workaround for the lack of rounding here. And please tell me if you spot any errors in the code.
