### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [akubera/bigdecimal-rs#16]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by akubera** [comment]
I was going to say we don't have a rustc-serialize dependency, but I see that there is residual code presenting serialization features at the top of lib.rs.

It looks like `num` is figuring out how to deal with serde 1.0 (https://github.com/rust-num/num/issues/281), so we will wait until that is figured out before implementing any serde serialization.
