### ISSUE TITLE
Serde feature

### ISSUE THREAD

**Issue by theduke** [akubera/bigdecimal-rs#18]
An optional serde integration would be nice to have, to avoid having to wrap BigDecimal in a newtype just for implementing (De)serialize.

I'd excpect it to serialize to a string and deserialize from strings and floats.

**Comment by rubdos** [comment]
Seems reasonable. One thing I still wonder about is [this](https://github.com/serde-rs/serde/issues/968), but that's currently a non issue here.

**Comment by akubera** [comment]
This has been implemented by @kestred (thank you!) and present in the 0.0.10 release that I just published.

**Comment by theduke** [comment]
Thanks, @kestred .
