### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by sgrif** [akubera/bigdecimal-rs#22]
Looks like there's a lot of stuff in master that hasn't been released. I'd like to be able to use the `into_bigint_and_exponent` method in Diesel. Any chance you could release soon?

**Comment by akubera** [comment]
Alright, version has been updated to 0.0.10 and published on crates. Thanks to everyone involved.

I still have a half-implemented context module that I have to finish, when that is finished I'll bump the version to 0.1.
