### ISSUE TITLE
Decimals considered equal might have different hash value

### ISSUE THREAD

**Issue by JasonXJ** [akubera/bigdecimal-rs#23]
For example
```rust
extern crate bigdecimal;

use std::hash::{Hash, Hasher};
use bigdecimal::BigDecimal;
use std::collections::hash_map::DefaultHasher;
use std::str::FromStr;

fn my_hash<T>(obj: T) -> u64
    where T: Hash
{
    let mut hasher = DefaultHasher::new();
    obj.hash(&mut hasher);
    hasher.finish()
}

pub fn main() {
    let x = BigDecimal::from_str("1.234").unwrap();
    let y = BigDecimal::from_str("1.234000").unwrap();
    assert_eq!(x, y);
    assert_ne!(my_hash(x), my_hash(y));
}
```

The reason is probably that `PartialEq` for `BigDecimal` is manually written to handle the scale, but `Hash` is derived.

**Comment by akubera** [comment]
I agree, if two values are considered equal then their hashes _must_ be the same. As currently implemented, trailing zeros are essentially stripped when comparing equality, so too should the hash.

The problem right now is the fact that our bigint is member is rather opaque - so "normalizing" it may require some copies, which is not optimal.

I don't think it'll be a complicated fix; I'll try to work on a solution soon.
