### ISSUE TITLE
Missing fmt::UpperHex and fmt::Binary traits.

### ISSUE THREAD

**Issue by jD91mZM2** [akubera/bigdecimal-rs#25]

**Comment by kestred** [comment]
For this issue, we don't necessarily have a well-defined binary representation of a `BigDecimal`.  (We'd also want to support `fmt::LowerHex`, etc, etc)

If there is a particular representation that would be useful to some specific application, it might be worth having multiple representations for BigDecimal as described in the Postscript (P.S.) of my comment https://github.com/akubera/bigdecimal-rs/issues/24#issuecomment-324047626.

**Comment by legolord208** [comment]
I'm not sure I understood your comment, but in `bc` it does this:

```
> obase=2
> 10.99
= 1010.1111110
```

**Comment by legolord208** [comment]
Update: Not sure if it deserves it's own separate issue, but `from_str_radix` should actually support setting the radix to anything other than 10... :stuck_out_tongue_closed_eyes:

**Comment by jD91mZM2** [comment]
#27
