### ISSUE TITLE
MulAssign and AddAssign implementations

### ISSUE THREAD

**Issue by rubdos** [akubera/bigdecimal-rs#5]
Would be very nice to have; iirc, `rust-num` doesn't have these. I wonder whether there's a valid reason for that.

**Comment by akubera** [comment]
I wanted to add those back in September, as I thought `Add` et al would have benefited by copying the "larger" of the two numbers, and then simply doing a `+=`. The `*Assign` traits were only marked stable in v1.8.0 and they had a strict 1.0.0 policy, so I never implemented it.

**Comment by rubdos** [comment]
For now, I treat them as a syntactic enhancement... I'm currently not interested in the most efficient implementation possible, but that might of course change in the future.

**Comment by rubdos** [comment]
I suppose I can close this now; as #7 is merged.
