### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by leodasvacas** [akubera/bigdecimal-rs#53]
First, thank you for this crate! Being on 0.0.x is annoying because you can't make a semver compatible upgrade, so for example the diesel dependency has to be bumped each time.

**Comment by rubdos** [comment]
I think we might even want to consider 1.0 at this point. Or am I wrong in thinking that the API didn't change a lot since its inception?

**Comment by akubera** [comment]
Ok. 0.1.0 is released. I was hoping to get a stable "context" struct working before the 0.1 milestone, but it's been a long time since I've even looked at that branch, so I guess it'll wait for 0.2.

**Comment by akubera** [comment]
oh, regarding 1.0, I think we definitely need a stable context interface for handling rounding & precision. If `num` is still hovering around 0.2, I don't feel any pressure to push for 1.0-level stability.
