### ISSUE TITLE
Serialize to number, not string

### ISSUE THREAD

**Issue by fenhl** [akubera/bigdecimal-rs#55]
The `serde` feature currently serializes `BigDecimal`s as strings. I find this surprising, since JSON does have a big-decimal number type. Ideally this should be used by default, but if that is not possible for whatever reason, something like a feature flag to enable it should exist.

**Comment by kestred** [comment]
JSON has no specific specification for what the limits are on a number, however generally, treating numbers as not `i32` or `f64` is an interoperability issue; see the below note in the spec.


[RFC 7159: The JavaScript Object Notation (JSON) Data Interchange Format](https://tools.ietf.org/html/rfc7159#section-6)

> This specification allows implementations to set limits on the range and precision of numbers accepted. Since software that implements IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision. A JSON number such as 1E400 or 3.141592653589793238462643383279 may indicate potential interoperability problems, since it suggests that the software that created it expects receiving software to have greater capabilities for numeric magnitude and precision than is widely available.

The current `BigDecimal` implementation will `deserialize` from either JSON numbers or strings, but will `serialize` to a `string`.

Serializing to strings makes no assumptions about what environment will later be de-serializing the value (in many languages, the caller has no control over how a value is deserialized and the language will deserialize a big decimal number into an f64 discarding precision; or may throw an error if it cannot be represented that way).  It is my assumption that folks using any `bigdecimal` are particularly concerned about the correctness and precision of values, and string de-serialization of numbers is reliably lossless. 

(Disclosure: I implemented serde support, but am not the crate maintainer)

**Comment by Kinrany** [comment]
RFC 7159 does not specify this explicitly, but here's how I read it:

* an implementation MUST parse numbers with any number of digits
* an implementation MAY set a limit on the range and precision. Numbers outside the range SHOULD be approximated with numbers inside the range

In other words, most implementations should not have trouble reading JSON documents that include numbers with arbitrary precision.

Furthermore any program that reads the contents of a JSON document generated with this library will have to be aware of arbitrarily long numbers regardless of whether they're being written as numbers or strings.

The only possible case where serializing big numbers as JSON numbers would be a problem is a case where:
* no JSON deserialization library capable of deserializing sub-documents (or just numbers) as strings is available
* a custom Serde serializer cannot be used
* a different language cannot be used to preprocess the document

Even in this rare case the outcome is a failure to parse, not an error.

The benefit of serializing big numbers as JSON numbers is the ability to express big number semantics at the JSON level, no extra domain knowledge required. In a language like Python this allows customizing the deserializer to handle strings and big numbers differently without considering the meaning of that data.

Overall I feel like serializing to numbers is obviously preferable, and it's worth looking at specific cases where serialization to strings is truly necessary and considering whether those cases are worth the trouble.
