### ISSUE TITLE
Add with_scale_round method

### ISSUE THREAD

**Issue by therustmonk** [akubera/bigdecimal-rs#59]
How about to add `with_scale_round` method that round a value instead of dropping digits? I can implement this if you agree that is a good idea. Or maybe you have workarounds for that?

**Comment by akubera** [comment]
[BigDecimal::with_scale_round](https://docs.rs/bigdecimal/latest/bigdecimal/struct.BigDecimal.html#method.with_scale_round) has been added in the v0.4 branches.
