### ISSUE TITLE
Consider to move the crait in `rust_num`

### ISSUE THREAD

**Issue by XVilka** [akubera/bigdecimal-rs#60]
Since the decimal arithmetic is crucial for business and financial applications, it makes sense to improve the visibility and make it more abstract (i.e. split from Postgres feature), and move into https://github.com/rust-num organization

cc @rust-num

Might be useful to create a generic implementation.

**Comment by rubdos** [comment]
Some history [here](https://github.com/rust-num/num/pull/193) and mostly also [here](https://github.com/rust-num/num/pull/224). TL;DR: this crate is a "testing ground" for what at first was `num`'s implementation for BigDecimal. There are a few "competing" implementations iirc, and the goal was to see which ones worked best and to test their APIs.

Could you elaborate on "make it more abstract"? Also, there's no direct connection between PostgrSQL and this crate. The only thing I know is that `diesel` uses the crate to *optionally* represent Postgres' Decimal type.

**Comment by XVilka** [comment]
@rubdos, basically the idea is to create some predefined set of the libraries suitable for "business applications", and big decimal arithmetic is one of the cornerstones of such a platform: https://internals.rust-lang.org/t/proposal-business-applications-working-group/10400
