### ISSUE TITLE
Print bigdecimal without trailing zeros 

### ISSUE THREAD

**Issue by incker** [akubera/bigdecimal-rs#85]
Code:

    let num1 = BigDecimal::from_str("1.000").unwrap();
    let num2 = BigDecimal::try_from(1.0f64).unwrap();

    println!("{}", num1.to_string());
    println!("{}", num2.to_string());

Output:

    1.000
    1.000000000000000

The question is how to make string from BigDecimal without trailing zeros
Thank you

**Comment by randomairborne** [comment]
Yeah, you can call [normalized()](https://docs.rs/bigdecimal/latest/bigdecimal/struct.BigDecimal.html#method.normalized)
