### ISSUE TITLE
Panic on round call

### ISSUE THREAD

**Issue by mashedcode** [akubera/bigdecimal-rs#90]
```rust
use bigdecimal::BigDecimal;
use std::str::FromStr;

fn main() {
    let decimal = BigDecimal::from_str("0.1165085714285714285714285714285714285714").unwrap();
    decimal.round(0); // called `Option::unwrap()` on a `None` value bigdecimal-rs/src/lib.rs:594:43
}
```

This panics. Complied against master.

**Comment by Niedzwiedzw** [comment]
same

**Comment by yamelsenih** [comment]
I think that a simple solution can be trunc the number if the digits is to long that i128 support

Best regards.

**Comment by yamelsenih** [comment]
Other solution is handle it as String instead

**Comment by akubera** [comment]
This has been fixed, and the example (for multiple rounding points) has been [added to the unit tests](https://github.com/akubera/bigdecimal-rs/blob/b80509a8be4d77149388311a486c754cb4bb1a76/src/lib.rs#L3095).
