### ISSUE TITLE
overflow on `PartialEq` for `BigDecimal`

### ISSUE THREAD

**Issue by austinabell** [akubera/bigdecimal-rs#93]
The following lines:
https://github.com/akubera/bigdecimal-rs/blob/272123eddc02aad5d1a331ded8eb6605ed2bea96/src/lib.rs#L799

https://github.com/akubera/bigdecimal-rs/blob/272123eddc02aad5d1a331ded8eb6605ed2bea96/src/lib.rs#L802

overflow whenever either `lhs` or `rhs` are opposite signs and the abs sum is `>u64::MAX`

repro:
```rust
    let a = BigDecimal::new(bigdecimal::num_bigint::BigInt::from(1), i64::MIN);
    let b = BigDecimal::new(bigdecimal::num_bigint::BigInt::from(1), 1);
    let _ = a == b;
```

Found during fuzzing https://github.com/near/borsh-rs/pull/91#issuecomment-1081896887

**Comment by akubera** [comment]
Fixed in new comparison implementation in v0.4.4. I just [added a test](https://github.com/akubera/bigdecimal-rs/commit/bf3fe0597a26fe19b9d41ce7ae96446f6f07ac26) for continued checking.

Thanks.
